// Auto-generated by scripts/build-templates.mjs
// Do not edit by hand. Edit src/ui/templates/*.{html,js} and rebuild.
export const templates = {
  admin_login_options: `<p style="margin:0 0 6px 0;"><b>Option A: Configuration UI</b></p>
<p style="margin:0 0 8px 0;">Login with your Admin Key.</p>
<input id="init-admin-key" type="password" placeholder="paste X-Admin-Key"
  style="width:100%;max-width:560px;padding:10px 12px;border:1px solid #cbd5e1;border-radius:8px;" />
<div style="margin-top:6px;font-size:12px;color:#475569;">API key is NOT stored in the browser</div>
<div style="margin-top:8px;">
  <button type="button" onclick="initAdminLogin()"
    style="padding:8px 12px;border:1px solid #0f172a;border-radius:8px;background:#111827;color:#fff;cursor:pointer;">Login</button>
</div>
<div id="init-admin-login-msg" style="margin-top:8px;color:#991b1b;"></div>
<p style="margin:14px 0 6px 0;"><b>Option B: Configure via API</b></p>
<p style="margin:0;"><a href="{{docs_url}}" target="_blank" rel="noopener noreferrer">API Documentation</a></p>
`,
  init_admin_login_js: `async function initAdminLogin() {
  const input = document.getElementById('init-admin-key');
  const msg = document.getElementById('init-admin-login-msg');
  const key = (input && input.value || '').trim();
  if (!key) {
    if (msg) msg.textContent = 'Enter your Admin API key first.';
    return;
  }
  try {
    const res = await fetch('{{admin_root}}/access-token', {
      method: 'POST',
      headers: { 'X-Admin-Key': key },
    });
    const text = await res.text();
    let payload = null;
    try { payload = JSON.parse(text); } catch {}
    if (!res.ok || !payload?.data?.access_token) {
      if (msg) msg.textContent = 'Login failed. Check your admin key and try again.';
      return;
    }
    try { sessionStorage.setItem('apiproxy_admin_access_token_v1', payload.data.access_token); } catch {}
    window.location.href = '{{admin_root}}';
  } catch {
    if (msg) msg.textContent = 'Login failed. Try again.';
  }
}
`,
  onboarding_header: `<div style="display:flex;align-items:center;gap:12px;margin:0 0 10px 0;">
  <img src="{{favicon_data_url}}" width="72" height="72" alt="API Transform Proxy icon" />
</div>
<h1 style="margin:0 0 14px 0;">Welcome!</h1>
`,
  page: `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>{{title}}</title>
  <link rel="icon" type="image/svg+xml" href="{{favicon_data_url}}" />
  <style>
    body { font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif; margin: 32px; max-width: 820px; }
    p { font-size: 16px; }
    code, pre { font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace; }
  </style>
</head>
<body>
  {{heading_html}}
  {{body_html}}
</body>
</html>
`,
  secret_field: `<div style="margin:14px 0;">
  <div style="font-weight:700;margin-bottom:6px;">{{label}}</div>
  <div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;">
    <input id="{{id}}" type="password" value="{{value}}" readonly
      style="flex:1;min-width:320px;padding:10px 12px;border:1px solid #cbd5e1;border-radius:8px;font-family:ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, monospace;" />
    <button type="button" data-toggle-for="{{id}}" onclick="toggleSecret('{{id}}')"
      style="{{button_style}}"{{disabled_attr}}>Show</button>
    <button type="button" data-copy-for="{{id}}" onclick="copySecret('{{id}}')"
      style="{{button_style}}"{{disabled_attr}}>Copy</button>
  </div>
  {{note_block}}
</div>
`,
  secret_field_js: `function toggleSecret(id) {
  const input = document.getElementById(id);
  const btn = document.querySelector('[data-toggle-for="' + id + '"]');
  if (!input || !btn || btn.disabled) return;
  const isHidden = input.type === 'password';
  input.type = isHidden ? 'text' : 'password';
  btn.textContent = isHidden ? 'Hide' : 'Show';
}

async function copySecret(id) {
  const input = document.getElementById(id);
  const btn = document.querySelector('[data-copy-for="' + id + '"]');
  if (!input || !btn || btn.disabled || !input.value) return;
  try {
    await navigator.clipboard.writeText(input.value);
    const old = btn.textContent;
    btn.textContent = 'Copied';
    setTimeout(() => { btn.textContent = old; }, 1200);
  } catch {}
}
`,
};
